[tool.poetry]
name = "test-a"
version = "1.0.0"
description = ""
authors = ["Ian Scott Knight <isk@alumni.stanford.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
